apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-ingest
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: ingest
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: ingest
  ports:
  - name: http
    port: 9200

