apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: data
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: data
  ports:
  - name: http
    port: 9200
  
